import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { ThemeColorProvider } from "../../context/theme-color-context";
import { GlobalSearch } from "@/components/global-search";
import ProgressBar from "@/components/setting/Appearance/route-progress";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={true}
          storageKey="theme-mode">
          <ThemeColorProvider>
            <GlobalSearch />
            <ProgressBar />
            {children}

          </ThemeColorProvider>
        </ThemeProvider>

      </body>
    </html>
  );
}
